// Generated by CoffeeScript 1.9.0
(function() {
  var A;

  A = (function() {
    function A() {}

    A.prototype.init = function() {
      return console.log("a");
    };

    return A;

  })();

  A.init = function() {
    return console.log("b");
  };

}).call(this);
