// Generated by CoffeeScript 1.9.0
(function() {
  var Controller, DB, DEVICE_ID, LAZY_SECONDS, NOTI_TIME, Notification, Pad, RATE, Status, lib, main;

  lib = {
    getParameterByName: function(name) {
      var regex, results;
      name = name.replace(/[\[]/, '\\[').replace(/[\]]/, '\\]');
      regex = new RegExp('[\\?&]' + name + '=([^&#]*)');
      results = regex.exec(location.search);
      if (results === null) {
        return '';
      } else {
        return decodeURIComponent(results[1].replace(/\+/g, ' '));
      }
    }
  };

  DEVICE_ID = "E";

  localStorage['deviceid'] = DEVICE_ID;

  $("title").text(DEVICE_ID);

  LAZY_SECONDS = 10;

  RATE = 2000;

  NOTI_TIME = 20000;

  Controller = (function() {
    var db, pad, _isLazy, _track, _trackCallback;

    db = void 0;

    pad = void 0;

    function Controller(_pad, _db, _at_notiController) {
      var main;
      this.notiController = _at_notiController;
      db = _db;
      pad = _pad;
      this.building = void 0;
      main = this;
      $('body').css('');
    }

    _track = function() {
      return db.track(_trackCallback).fail(function() {
        console.log('trace_fail , continuing');
        return setTimeout(_track, RATE);
      });
    };

    _isLazy = function() {
      var d;
      d = new Date();
      return ((d.getTime() - _lastMoveTime) / 1000) > LAZY_SECONDS;
    };

    _trackCallback = function(data) {
      var devId, status, _callback, _i, _len;
      console.log("tracked.", data);
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        status = data[_i];
        status = new Status(status);
        if (status.isRead() || status.isSelf()) {

        } else {
          if (status.isPad() && (status.isCHECK_IN() || status.isBUILD_UP() || status.isLOOK_UP())) {
            console.log(status);
            devId = status.device;
            _callback = function(data) {
              var b, _j, _len1, _results;
              console.log(data);
              if ($.isArray(data)) {
                pad.remove(devId);
                _results = [];
                for (_j = 0, _len1 = data.length; _j < _len1; _j++) {
                  b = data[_j];
                  _results.push(pad.show(devId, b));
                }
                return _results;
              } else if ($.isPlainObject(data)) {
                pad.remove(devId);
                return pad.show(devId, data);
              } else {
                return console.warn(data, 'doesnt got its type');
              }
            };
            switch (status.object_type) {
              case 'G':
                db.getTag(status.oid, _callback);
                break;
              case 'B':
                db.getBuilding(status.oid, _callback);
                break;
              case 'T':
                db.getType(status.oid, _callback);
                break;
              default:
                console.warn('no object_type');
            }
            db.markReadStatus(status);
          }
        }
      }
      return setTimeout(_track, RATE);
    };

    Controller.prototype.track = function() {
      console.log("start tracking");
      return setTimeout(_track, RATE);
    };

    Controller.prototype.busy = function() {
      var d, _lastMoveTime;
      d = new Date();
      return _lastMoveTime = d.getTime();
    };

    Controller.prototype.wait = function() {};

    Controller.prototype.isLazy = function() {
      return _isLazy();
    };

    Controller.prototype.addStatus = function(data, callback) {
      return db.addStatus(data, callback);
    };

    return Controller;

  })();

  Status = (function() {
    var comingData, thisStatus;

    thisStatus = void 0;

    comingData = void 0;

    function Status(data) {
      var attrname, e, test;
      thisStatus = this;
      comingData = data;
      for (attrname in data) {
        this[attrname] = data[attrname];
      }
      if (!this.isBUILDING()) {
        try {
          this.object = this.object.replace(/(\r\n|\n|\r)/gm, "");
          test = JSON.parse(this.object);
        } catch (_error) {
          e = _error;
          console.error(e, this.object);
          test = {
            bid: "1",
            bname: "映山華廈"
          };
        }
        this.object_real = test;
      }
      this["event"] = this.getEvent();
      console.log(this["event"]);
    }

    Status.prototype.isRead = function() {
      if (this.done) {
        return this.done.indexOf(DEVICE_ID) >= 0;
      } else {
        return false;
      }
    };

    Status.prototype.isSelf = function() {
      return this.device === DEVICE_ID;
    };

    Status.prototype.isPad = function() {
      return this.device === "A" || this.device === "B" || this.device === "C";
    };

    Status.prototype.isDesk = function() {
      return this.device === "D";
    };

    Status.prototype.isTop = function() {
      return this.device === "E";
    };

    Status.prototype.isProject = function() {
      return this.device === "F";
    };

    Status.prototype.isNull = function() {
      return this.device !== "A" && this.device !== "B" && this.device !== "C" && this.device !== "D" && this.device !== "E" && this.device !== "F";
    };

    Status.prototype.isCHECK_IN = function() {
      return this.behavior === "LIVE_IN";
    };

    Status.prototype.isLOOK_UP = function() {
      return this.behavior === "LOOK_UP";
    };

    Status.prototype.isBUILDING = function() {
      return this.behavior === "BUILD_UP";
    };

    Status.prototype.isBUILD_UP = function() {
      return this.behavior === "BUILD_UP_after";
    };

    Status.prototype.isBUILD_UP_RETURN = function() {
      return this.behavior === "BUILD_UP_return";
    };

    Status.prototype.liveTime = function() {
      var d, o;
      o = new Date(this.time);
      d = new Date();
      return Math.ceil((d.getTime() - o.getTime()) / 1000);
    };

    Status.prototype.getEvent = function() {
      if (this.isNull()) {
        return "DeviceNull";
      }
      if (this.isSelf()) {
        return "self";
      }
      if (this.isPad()) {
        if (this.isBUILDING()) {
          return "otherPad.building";
        }
        if (this.isBUILD_UP()) {
          return "otherPad.buildUp";
        }
        if (this.isCHECK_IN()) {
          return "otherPad.liveIn";
        }
        if (this.isLOOK_UP()) {
          if (this.object_type === "B") {
            return "otherPad.lookUp.building";
          }
          if (this.object_type === "T") {
            return "otherPad.lookUp.type";
          }
          if (this.object_type === "G") {
            return "otherPad.lookUp.tag";
          }
        }
      } else if (this.isDesk()) {
        if (this.isLOOK_UP()) {
          return "desk.lookUp";
        }
        if (this.isBUILD_UP_RETURN()) {
          return "desk.building";
        }
      } else {
        console.log(comingData, "unsolve");
        return "unsolve";
      }
    };

    return Status;

  })();

  DB = (function() {
    function DB() {}

    DB.prototype.pull = function(url, callback) {
      return $.get(url, callback).fail(function(j, s, e) {
        return console.log(j.responseText, s, e);
      });
    };

    DB.prototype.o = function(url, callback) {
      return $.get(url, callback).fail(function(j, s, e) {
        return console.log(j.responseText, s, e);
      });
    };

    DB.prototype.push = function(url, data, callback) {
      return $.post(url, data).done(callback);
    };

    DB.prototype.clearStatus = function(match, callback) {
      if (!callback) {
        callback = function() {};
      }
      console.log(callback);
      if (!match) {
        return this.push("data/clearStatus.php", {
          device: DEVICE_ID
        }, function(data, textStatus) {
          callback();
          return console.log(data, textStatus, "Status of " + DEVICE_ID + " is deleted.");
        });
      } else if (match.statusid) {
        return this.push("data/clearStatus.php", {
          statusid: match.statusid
        }, function(data, textStatus) {}, callback(), console.log(textStatus, "Status " + status.statusid + " is deleted."));
      }
    };

    DB.prototype.markReadStatus = function(status) {
      var data;
      data = {
        done: DEVICE_ID,
        statusid: status.statusid
      };
      return this.push("data/updateStatus.php", data, function() {
        return console.log("Status " + status.statusid + " is mark read.");
      });
    };

    DB.prototype.addStatus = function(data, callback) {
      var lc, lco, _addStatus;
      lco = JSON.parse(data.object);
      lc = 0;
      switch (data.object_type) {
        case "T":
          lc = lco.cid;
          break;
        case "B":
          lc = lco.bid;
          break;
        case "G":
          lc = lco.gid;
          break;
        default:
          console.warn("Rn.expect object_type,now set oid to 1");
      }
      console.log(lc, lco);
      _addStatus = function() {
        return this.push("data/addStatus.php", {
          deviceid: DEVICE_ID,
          behavior: data.behavior,
          object_type: data.object_type,
          object: data.object,
          oid: lc,
          time: new Date()
        }, function() {
          if (callback) {
            callback();
          }
          return console.log("" + data.behavior);
        });
      };
      return this.clearStatus().success(_addStatus.bind(this));
    };

    DB.prototype.getTag = function(gid, callback) {
      console.log(gid, callback);
      return $.get("http://192.168.1.100/co-construction/api/select_tag.php?gid=" + gid, function(data) {
        data = JSON.parse(data);
        console.log("select_tag", data);
        if ($.isFunction(callback)) {
          return callback(data);
        }
      });
    };

    DB.prototype.getType = function(tid, callback) {
      console.log(tid, callback);
      return $.get("http://192.168.1.100/co-construction/api/select_type.php?cid=" + tid, function(data) {
        data = JSON.parse(data);
        console.log("select_type", data);
        if ($.isFunction(callback)) {
          return callback(data);
        }
      });
    };

    DB.prototype.getBuilding = function(bid, callback) {
      console.log(bid, callback);
      return $.get("http://192.168.1.100/co-construction/api/select_building.php?bid=" + bid, function(data) {
        data = JSON.parse(data);
        console.log("select_building", data);
        if ($.isFunction(callback)) {
          return callback(data);
        }
      });
    };

    DB.prototype.track = function(callback) {
      return this.pull("data/pullStatus.php", callback);
    };

    return DB;

  })();

  Pad = (function() {
    var $body;

    $body = $("body");

    function Pad(_at_id) {
      this.id = _at_id;
      $(document).on('click', '.noti span.close', function(e) {
        return $(this).closest('.noti').addClass('animated fadeOutLeft');
      });
      $(document).one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', '.fadeOutLeft', function(e) {
        console.info($(this));
        return $(this).remove();
      });
      this.$infoA = $("#INFO_A");
      this.$infoB = $("#INFO_B");
      this.$infoC = $("#INFO_C");
    }

    Pad.prototype.remove = function(devId) {
      return $("." + devId).remove();
    };

    Pad.prototype.show = function(devId, building) {
      return $("body").append("<div class=\"" + devId + " box\" style=\"left:" + building.x + "px ; top:" + building.y + "px\"></div>");
    };

    Pad.prototype.noti = function(noti) {
      console.log("apd", noti);
      noti.appendTo("#notiContainer");
      return setTimeout(function() {
        return noti.addClass('animated fadeOutLeft');
      }, NOTI_TIME);
    };

    Pad.prototype.navTo = function(padObject) {
      $(".active").not(padObject).fadeOut();
      return padObject.fadeIn(function() {
        return padObject.addClass("active");
      });
    };

    Pad.prototype.currentPage = function() {
      var a;
      a = $(".Page.active");
      console.log(a.length, a);
      return a;
    };

    return Pad;

  })();

  Notification = (function() {
    var _getNotiStructure;

    _getNotiStructure = function(noti) {
      return "<a class=\"noti animated fadeInLeft\">\n  <p class=\"" + noti[1] + "\" data-ajax=\"" + noti[2] + "\">" + noti[0] + "</p>\n  <span class='close'></span>\n</a>";
    };

    function Notification(status) {
      var data, jq;
      status.objString = this.object2String(status);
      status.href = this.getHref(status);
      data = this.getData(status);
      console.log(data);
      jq = $(_getNotiStructure(data));
      $.extend(this, jq);
    }

    Notification.prototype.getData = function(status) {
      var id, padStr, url;
      id = status.device;
      url = status.href;
      padStr = "<span class=\"" + id + "\">平板" + id + "</span>";
      switch (status.event) {
        case "otherPad.building":
          return [padStr + "正在建造中！", "noClick disabled", url];
        case "otherPad.buildUp":
          return [padStr + "建造了" + status.objString + "！", "from" + id + " toLookUp building", url];
        case "otherPad.liveIn":
          return [padStr + "入住了" + status.objString, "from" + id + " toLookUp building", url];
        case "otherPad.lookUp.building":
          return [padStr + "正在查找" + status.objString, "from" + id + " toLookUp building", url];
        case "otherPad.lookUp.type":
          return [padStr + "正在查找" + status.objString, "from" + id + " toLookUp type", url];
        case "otherPad.lookUp.tag":
          return [padStr + "正在查找" + status.objString, "from" + id + " toLookUp tag", url];
        case "desk.lookUp":
          return ["<span class='D'>共構桌</span>上選取了" + status.objString, "from" + id + " toLookUp building", url];
        case "desk.building":
          return ["<span class='D'>共構桌</span>上有一筆建造" + status.objString, "from" + id + " toLookUp building", url];
        default:
          alert(status.event);
          return ["無", "hidden", "url"];
      }
    };

    Notification.prototype.object2String = function(status) {
      var span;
      span = function(name) {
        return "<br>「<span class=\"highlight\">" + name + "</span>」";
      };
      console.log(status.object_real);
      switch (status.object_type) {
        case "B":
          return "建築:" + (span(status.object_real.bname));
        case "T":
          return "建築類型:" + (span(status.object_real.tname));
        case "G":
          return "建築標籤:" + (span(status.object_real.gname));
      }
    };

    Notification.prototype.getHref = function(status) {
      var href;
      href = "";
      switch (status.object_type) {
        case "B":
          href = "page=infoA&bid=" + status.object_real.bid;
          break;
        case "T":
          href = "page=infoB&cid=" + status.object_real.cid;
          break;
        case "G":
          href = "page=infoC&gid=" + status.object_real.gid;
      }
      if (href.length > 0) {
        return href;
      }
    };

    return Notification;

  })();

  this.Pad = Pad;

  this.Notification = Notification;

  this.DB = DB;

  this.Controller = Controller;

  this.Status = Status;

  main = new Controller(new Pad(), new DB());

  main.track();

}).call(this);
