// Generated by CoffeeScript 1.9.0
(function() {
  var ButtonListener, SwitchController;

  this.localhost = "140.119.134.100";

  SwitchController = (function() {
    var statusController;

    statusController = void 0;

    function SwitchController(_statusController) {
      statusController = _statusController;
    }

    SwitchController.prototype.prepareStatus = function(behavior, object_type) {
      var obj;
      return obj = {
        behavior: behavior,
        object_type: object_type
      };
    };

    SwitchController.prototype.ajaxPage = function(href, status) {
      console.log(status);
      return $.get("http://" + localhost + "/co-construction/php/controller.php?" + href, function(data, textStatus) {
        var $curPage, $newPage;
        if (textStatus !== "success") {
          return alert("get page failed");
        } else if (textStatus === "success") {
          $curPage = $('.Page.active');
          $newPage = $("<div class='Page' style='opacity:0.0'>" + data + "</div>").remove('video');
          $newPage = $newPage.appendTo('#pageContainer');
          if (status !== false) {
            setTimeout(function() {
              status.object = localStorage['status'];
              return statusController.addStatus(status);
            }, 200);
          }
          return setTimeout(function() {
            return $curPage.animate({
              opacity: 0.0
            }, 600, function() {
              $curPage.remove();
              return $newPage.delay(100).animate({
                opacity: 1
              }, 600).promise().done(function() {
                $newPage.addClass("active");
                if (typeof effectAnimate === "function") {
                  return effectAnimate();
                }
              });
            });
          }, 800);
        }
      });
    };

    return SwitchController;

  })();

  ButtonListener = (function() {
    var switchController, _main;

    switchController = void 0;

    _main = void 0;

    function ButtonListener(_switchController) {
      _main = this;
      switchController = _switchController;
      $(document).on("click", ".toLookUp.building", function(e) {
        var status;
        e.preventDefault();
        status = switchController.prepareStatus("LOOK_UP", "B");
        switchController.ajaxPage($(this).data('ajax'), status);
        return false;
      });
      $(document).on("click", ".toLookUp.type", function(e) {
        var status;
        e.preventDefault();
        status = switchController.prepareStatus("LOOK_UP", "T");
        switchController.ajaxPage($(this).data('ajax'), status);
        return false;
      });
      $(document).on("click", ".toLookUp.tag", function(e) {
        var status;
        e.preventDefault();
        status = switchController.prepareStatus("LOOK_UP", "G");
        switchController.ajaxPage($(this).data('ajax'), status);
        return false;
      });
      $(document).on("click", ".noti", function(e) {
        var action;
        return action = $(this).data("action");
      });
      $(document).on("click", ".toLookUp.tag", function(e) {
        var status;
        e.preventDefault();
        status = switchController.prepareStatus("LOOK_UP", "G");
        switchController.ajaxPage($(this).data('ajax'), status);
        return false;
      });
      $(document).on("click", ".toFinish", function(e) {
        e.preventDefault();
        return switchController.ajaxPage($(this).data('ajax'), false);
      });
    }

    return ButtonListener;

  })();

  this.SwitchController = SwitchController;

  this.ButtonListener = ButtonListener;

  this.radian = true;

  $(function() {
    var db, initStatus, pad, statusController, switchController;
    pad = new Pad();
    db = new DB();
    statusController = new Controller(pad, db);
    switchController = new SwitchController(statusController);
    ButtonListener = new ButtonListener(switchController);
    statusController.track();
    initStatus = switchController.prepareStatus("LOOK_UP", "B");
    return switchController.ajaxPage("page=infoA&bid=1", initStatus);
  });

}).call(this);
