// Generated by CoffeeScript 1.9.0
(function() {
  var INFO_A, INFO_B, INFO_C;

  INFO_A = (function() {
    function INFO_A() {
      this.dom = $("#INFO_A");
      this.typeDom = $(".infoABox");
      this.tagDom = $(".infoABox").textTypingL.infoABoxBottom.infoAContainer.infoABuildingName.infoABuildingTypeText.infoABuildingContext.infoAtagBox.infoAtag.infoBBuildingContent;
    }

    INFO_A.prototype.showAinfo = function() {};

    INFO_A.prototype.showTop3Type = function(json) {
      var i, obj, _i, _len, _results;
      _results = [];
      for (i = _i = 0, _len = json.length; _i < _len; i = ++_i) {
        obj = json[i];
        _results.push($(this.dom).find(".type")[i].html());
      }
      return _results;
    };

    INFO_A.prototype.showTop3Tag = function(json) {
      var i, obj, _i, _len, _results;
      _results = [];
      for (i = _i = 0, _len = json.length; _i < _len; i = ++_i) {
        obj = json[i];
        _results.push($(this.dom).find(".tag")[i].html());
      }
      return _results;
    };

    return INFO_A;

  })();

  INFO_B = (function() {
    function INFO_B() {}

    INFO_B.prototype.show10Type = function() {};

    INFO_B.prototype.showTop3Tag = function() {};

    return INFO_B;

  })();

  INFO_C = (function() {
    function INFO_C() {}

    INFO_C.prototype.showCinfo = function() {};

    INFO_C.prototype.showCelements = function() {};

    return INFO_C;

  })();

}).call(this);
