// Generated by CoffeeScript 1.9.0
(function() {
  $(function() {
    var ajaxB, updateStatus;
    updateStatus = function($newPage) {
      var json;
      return json = $newPage.find("#phpData").val();
    };
    ajaxB = function(href) {
      return $.get("http://140.119.134.100/co-construction/php/controller.php?" + href, function(data) {
        var $curPage, $newPage;
        $curPage = $('.Page.active');
        $newPage = $("<div class='Page' style='opacity:0.05'>" + data + "</div>").remove('video');
        $newPage = $newPage.appendTo('#pageContainer');
        return setTimeout(function() {
          return $curPage.animate({
            opacity: 0.05
          }, 600, function() {
            $curPage.remove();
            return $newPage.delay(100).animate({
              opacity: 1
            }, 600, function() {
              return $newPage.addClass("active");
            });
          });
        }, 800);
      });
    };
    ajaxB("page=infoA&bid=1");
    return $(document).on('click', '.toLookUp.tag', function(e) {
      var href;
      href = $(this).data("ajax");
      ajaxB(href);
      e.preventDefault();
      return false;
    });
  });

}).call(this);
