$ ->


  

  ajaxB = (href) ->
    $.get "http://140.119.134.100/co-construction/php/controller.php?#{href}", (data) ->
      $curPage = $ '.Page.active'
      $newPage = $("<div class='Page' style='opacity:0.05'>#{data}</div>").remove 'video'
      $newPage = $newPage.appendTo '#pageContainer'

      setTimeout ()->

        $curPage.animate { opacity: 0.05 }, 600 , ()->
          $curPage.remove()

          $newPage.delay(100).animate { opacity: 1 }, 600 , ()->
            $newPage.addClass "active"

  ajaxB ("page=infoA&bid=1")


  $(document).on 'click','.toLookUp.tag', (e)->
    href = $(this) .data "ajax"
    ajaxB href
    e.preventDefault()
    false


# ---
# generated by js2coffee 2.0.3


$( () ->







)
